#pragma once

static const char ONBOARD_HTML[] =
"<!DOCTYPE html><html><head>"
"<meta charset='utf-8'>"
"<meta name='viewport' content='width=device-width,initial-scale=1'>"
"<title>Magic Badge Setup</title>"
"<style>"
"*{box-sizing:border-box;margin:0;padding:0}"
"body{font-family:-apple-system,sans-serif;background:#f5f5f5;color:#333;padding:16px;max-width:480px;margin:0 auto}"
"h1{text-align:center;margin:16px 0;font-size:1.4em;color:#1a73e8}"
".card{background:#fff;border-radius:12px;margin:12px 0;box-shadow:0 1px 3px rgba(0,0,0,.12);overflow:hidden}"
".card-hdr{display:flex;justify-content:space-between;align-items:center;padding:14px 16px;cursor:pointer;user-select:none;font-weight:600;font-size:.95em}"
".card-hdr::after{content:'\\25BC';font-size:.7em;transition:transform .2s}"
".card.collapsed .card-hdr::after{transform:rotate(-90deg)}"
".card.collapsed .card-body{display:none}"
".card-body{padding:0 16px 16px}"
"label{display:block;margin:10px 0 4px;font-size:.85em;color:#555}"
"input,select{width:100%;padding:10px 12px;border:1px solid #ddd;border-radius:8px;font-size:.95em;outline:none}"
"textarea{width:100%;padding:10px 12px;border:1px solid #ddd;border-radius:8px;font-size:.95em;outline:none;resize:vertical;min-height:110px}"
"input:focus,select:focus,textarea:focus{border-color:#1a73e8}"
".btn{display:block;width:100%;padding:12px;border:none;border-radius:8px;font-size:1em;font-weight:600;cursor:pointer;margin:8px 0}"
".btn-scan{background:#e8f0fe;color:#1a73e8}"
".btn-save{background:#1a73e8;color:#fff;margin-top:20px;font-size:1.1em}"
".btn:active{opacity:.8}"
".ap-list{max-height:200px;overflow-y:auto;border:1px solid #ddd;border-radius:8px;margin:8px 0}"
".ap-item{padding:10px 12px;border-bottom:1px solid #eee;cursor:pointer;display:flex;justify-content:space-between}"
".ap-item:last-child{border-bottom:none}"
".ap-item:active{background:#e8f0fe}"
".ap-rssi{color:#888;font-size:.85em}"
".ap-lock::before{content:'\\1F512';font-size:.75em;margin-right:4px}"
".status{text-align:center;padding:20px;color:#1a73e8;font-size:1.1em;display:none}"
".row{display:flex;gap:8px}"
".row .btn{margin:8px 0}"
".hint{font-size:.8em;color:#777;margin-top:6px;line-height:1.4}"
".hint.err{color:#c5221f}"
".hint.ok{color:#137333}"
"</style></head><body>"
"<h1>Magic Badge Setup</h1>"
"<p style='text-align:center;color:#666;font-size:.9em;margin-bottom:12px'>"
"This local portal remains available at 192.168.4.1 for later updates."
"</p>"

/* WiFi section (expanded by default) */
"<div class='card' id='sec-wifi'>"
"<div class='card-hdr' onclick='toggle(this)'>WiFi Configuration</div>"
"<div class='card-body'>"
"<button class='btn btn-scan' onclick='scan()'>Scan WiFi Networks</button>"
"<div class='ap-list' id='ap-list' style='display:none'></div>"
"<label>SSID</label>"
"<input id='ssid' placeholder='WiFi network name'>"
"<label>Password</label>"
"<input id='password' type='password' placeholder='WiFi password'>"
"</div></div>"

/* LLM section */
"<div class='card collapsed' id='sec-llm'>"
"<div class='card-hdr' onclick='toggle(this)'>LLM Configuration</div>"
"<div class='card-body'>"
"<label>API Key</label>"
"<input id='api_key' type='password' placeholder='API key'>"
"<label>Model</label>"
"<input id='model' placeholder='claude-opus-4-5 / qwen-max' value='claude-opus-4-5'>"
"<label>Provider</label>"
"<select id='provider'>"
"<option value='anthropic'>Anthropic</option>"
"<option value='openai'>OpenAI</option>"
"<option value='openrouter'>OpenRouter</option>"
"<option value='nvidia'>NVIDIA NIM</option>"
"<option value='qwen'>Qwen (DashScope)</option>"
"<option value='deepseek'>DeepSeek</option>"
"</select>"
"<label>Identity System Prompt</label>"
"<textarea id='system_prompt' placeholder='Optional identity block shown at the top of system prompt'></textarea>"
"</div></div>"

/* Telegram section */
"<div class='card collapsed' id='sec-tg'>"
"<div class='card-hdr' onclick='toggle(this)'>Telegram Bot</div>"
"<div class='card-body'>"
"<label>Bot Token</label>"
"<input id='tg_token' placeholder='123456:ABC-DEF...'>"
"</div></div>"

/* Feishu section */
"<div class='card collapsed' id='sec-feishu'>"
"<div class='card-hdr' onclick='toggle(this)'>Feishu</div>"
"<div class='card-body'>"
"<label>App ID</label>"
"<input id='feishu_app_id' placeholder='cli_xxxx'>"
"<label>App Secret</label>"
"<input id='feishu_app_secret' type='password' placeholder='App Secret'>"
"</div></div>"

/* Proxy section */
"<div class='card collapsed' id='sec-proxy'>"
"<div class='card-hdr' onclick='toggle(this)'>Proxy</div>"
"<div class='card-body'>"
"<label>Host</label>"
"<input id='proxy_host' placeholder='192.168.1.100'>"
"<label>Port</label>"
"<input id='proxy_port' type='number' placeholder='7890'>"
"<label>Type</label>"
"<select id='proxy_type'>"
"<option value=''>None</option>"
"<option value='http'>HTTP</option>"
"<option value='socks5'>SOCKS5</option>"
"</select>"
"</div></div>"

/* Search section */
"<div class='card collapsed' id='sec-search'>"
"<div class='card-hdr' onclick='toggle(this)'>Search</div>"
"<div class='card-body'>"
"<label>Brave Search API Key</label>"
"<input id='search_key' type='password' placeholder='BSA...'>"
"<label>Tavily API Key</label>"
"<input id='tavily_key' type='password' placeholder='tvly-...'>"
"</div></div>"

/* Character section — what the badge says when it talks as you */
"<div class='card collapsed' id='sec-character'>"
"<div class='card-hdr' onclick='toggle(this)'>Character</div>"
"<div class='card-body'>"
"<label>Display Name</label>"
"<input id='buddy_name' maxlength='31' placeholder='Your public name'>"
"<label>Bio</label>"
"<textarea id='buddy_bio' maxlength='2047' placeholder='A short intro about yourself'></textarea>"
"<label>Appearance</label>"
"<textarea id='buddy_appearance' maxlength='1023' placeholder='What you look like: height, hair, what you are wearing today'></textarea>"
"<label>Belongings</label>"
"<textarea id='buddy_belongings' maxlength='1023' placeholder='What you carry: camera, sketchbook, a very old thermos'></textarea>"
"<label>Character (three words)</label>"
"<input id='buddy_traits' maxlength='255' placeholder='curious, blunt, easily amused'>"
"<label>World tech level</label>"
"<input id='buddy_tech_level' maxlength='127' placeholder='The world this character lives in, e.g. swords and spirit magic, no electricity'>"
"<label>How you speak</label>"
"<textarea id='buddy_speech' maxlength='255' placeholder='Dialect and register, e.g. Mandarin without Cantonese; short clipped sentences'></textarea>"
"<label>What you know</label>"
"<textarea id='buddy_knows' maxlength='511' placeholder='The things this character has heard of, e.g. Liyue, the adepti, Vision bearers, the escort trade. Anything not listed, they will not recognise'></textarea>"
"<label style='margin-top:16px'>Scene (where you meet)</label>"
"<textarea id='buddy_scene' maxlength='1279' placeholder='Where the two of you are standing when you meet. Write what is there: objects, plants, animals, sounds, smells, what is happening. The more nameable things it holds, the more the conversation has to talk about — the sandbox measured a one-line scene giving roughly one line of material, and a detailed one giving five to eight.'></textarea>"
"<div class='hint'>Not part of the character: a scene belongs to an encounter, and both "
"badges keep their own copy rather than exchanging one. Generation is offline — upload a "
"scene card, or write it here.</div>"
"<label style='margin-top:16px'>Scene card (JSON)</label>"
"<div class='row'>"
"<button class='btn btn-scan' type='button' onclick='sceneDownload()'>Download</button>"
"<button class='btn btn-scan' type='button' onclick=\"document.getElementById('scene_file').click()\">Upload</button>"
"</div>"
"<input id='scene_file' type='file' accept='.json,application/json' style='display:none' onchange='sceneUpload(event)'>"
"<div class='hint' id='scene_msg'>The scene alone, so one file can be shared between "
"badges or swapped without touching either character. Press Save to keep it.</div>"
"<label style='margin-top:16px'>Character card (JSON)</label>"
"<div class='row'>"
"<button class='btn btn-scan' type='button' onclick='cardDownload()'>Download</button>"
"<button class='btn btn-scan' type='button' onclick=\"document.getElementById('card_file').click()\">Upload</button>"
"</div>"
"<input id='card_file' type='file' accept='.json,application/json' style='display:none' onchange='cardUpload(event)'>"
"<div class='hint' id='card_msg'>Export or restore every character field as one file. "
"Uploading fills the form; press Save to keep it.</div>"
"<label style='margin-top:16px'>Cool-down (minutes)</label>"
"<div class='hint'>How long this badge refuses to start another conversation after "
"finishing one. Both are per badge, not per peer: the second one gates everyone.</div>"
"<label>After talking to the same badge</label>"
"<input id='buddy_cool_peer_min' type='number' min='0.2' max='10080' step='0.5' placeholder='3'>"
"<label>After any conversation</label>"
"<input id='buddy_cool_session_min' type='number' min='0.2' max='10080' step='0.5' placeholder='3'>"
"<div class='hint'>Three minutes suits two badges sitting side by side. For a pair "
"that meets once a day, hours is closer to the intent.</div>"
"<label style='display:flex;align-items:center;gap:8px'>"
"<input id='buddy_privacy' type='checkbox' style='width:auto'> Private Mode (stop broadcasting)"
"</label>"
"</div></div>"

/* Features section */
"<div class='card collapsed' id='sec-features'>"
"<div class='card-hdr' onclick='toggle(this)'>Features</div>"
"<div class='card-body'>"
"<style>"
".feature-item{display:flex;align-items:flex-start;gap:12px;margin:12px 0}"
".feature-item input[type='checkbox']{width:16px;height:16px;margin-top:4px;cursor:pointer}"
".feature-item input[type='checkbox']:checked{accent-color: #1a73e8;width:16px;height:16px;margin-top:4px;cursor:pointer}"
".feature-content{flex:1}"
".feature-title{font-weight:700;line-height:1.3;margin-bottom:4px}"
".feature-desc{font-size:.85em;color:#666;line-height:1.4}"
"</style>"
"<div class='feature-item'>"
"<input id='telegram_bot' type='checkbox'>"
"<div class='feature-content'>"
"<div class='feature-title'>Telegram Bot</div>"
"<div class='feature-desc'>Enable communication through Telegram bot interface</div>"
"</div>"
"</div>"
"<div class='feature-item'>"
"<input id='feishu_bot' type='checkbox'>"
"<div class='feature-content'>"
"<div class='feature-title'>Feishu Bot</div>"
"<div class='feature-desc'>Enable communication through Feishu bot interface</div>"
"</div>"
"</div>"
"</div></div>"

"<button class='btn btn-save' onclick='save()'>Save &amp; Restart</button>"
"<div class='status' id='status'>Saving... Device will restart.</div>"

"<script>"
"function toggle(el){"
"el.parentElement.classList.toggle('collapsed')}"


"function loadConfig(){"
"fetch('/config').then(r=>r.json()).then(cfg=>{"
"Object.keys(cfg).forEach(k=>{"
"var el=document.getElementById(k);"
"if(el && cfg[k] !== undefined && cfg[k] !== null){"
"if(el.type === 'checkbox'){"
"el.checked=cfg[k]}"
"else if(el.tagName === 'SELECT'){"
"el.value=cfg[k]}"
"else{el.value=cfg[k]}"
"}"
"});"
"var lc=document.getElementById('last_channel_display');"
"if(lc){"
"var ch=cfg.last_src_channel||'';"
"var cid=cfg.last_src_chat_id||'';"
"lc.textContent=ch?(ch+' / '+cid):'(none yet)';"
"}"
"applyBuildAvailability(cfg);"
"}).catch(()=>{})}"

"function scan(){"
"var btn=event.target;btn.textContent='Scanning...';btn.disabled=true;"
"fetch('/scan').then(r=>r.json()).then(list=>{"
"var el=document.getElementById('ap-list');el.style.display='block';el.innerHTML='';"
"list.forEach(ap=>{"
"var d=document.createElement('div');d.className='ap-item';"
"d.innerHTML='<span>'+(ap.auth?'<span class=ap-lock></span>':'')+ap.ssid+'</span><span class=ap-rssi>'+ap.rssi+' dBm</span>';"
"d.onclick=function(){document.getElementById('ssid').value=ap.ssid};"
"el.appendChild(d)});"
"btn.textContent='Scan WiFi Networks';btn.disabled=false;"
"}).catch(()=>{btn.textContent='Scan WiFi Networks';btn.disabled=false})}"

// ── Character card: export / import ────────────────────────────
// Cards are also authored offline, and a character survives being moved between
// badges, so the portal has to be able to hand one out and take one in.  Keys are
// the same buddy_* names the form and /config use, which keeps one vocabulary
// across the page, the API and the file, and makes the JSON readable next to the
// form field it fills.
//
// A card is the owner's OWN character: name, bio, appearance, belongings,
// traits, the world's tech level, speech and the knowledge boundary.  The peer's
// half is not in here and cannot be — it is not stored.
//
// Limits are byte counts that mirror main/buddy/buddy.h.  They are checked here
// because the device copies with snprintf(), which truncates silently: an
// over-long field would import looking fine and save short.
"var CARD_KEYS=['buddy_name','buddy_bio','buddy_appearance','buddy_belongings',"
"'buddy_traits','buddy_tech_level','buddy_speech','buddy_knows'];"
"var CARD_MAX={buddy_name:31,buddy_bio:2047,buddy_appearance:1023,buddy_belongings:1023,"
"buddy_traits:255,buddy_tech_level:127,buddy_speech:255,buddy_knows:511};"
"var CARD_VERSION=1;"
// A scene card is its own format, separate from the character card: a scene
// belongs to an encounter, not to a character, so one file can be shared between
// two badges or swapped without touching either character. 1279 = the firmware's
// BUDDY_SCENE_LEN of 1280 less the terminator.
"var SCENE_VERSION=1;"
"var SCENE_MAX=1279;"

"function cardBytes(s){"
"if(typeof TextEncoder!=='undefined'){return new TextEncoder().encode(s).length}"
"return unescape(encodeURIComponent(s)).length;"
"}"
"function cardMsg(text,kind){"
"var el=document.getElementById('card_msg');"
"if(!el) return;"
"el.textContent=text;"
"el.className='hint'+(kind?' '+kind:'');"
"}"
// Same shape, its own element: the two cards report into different lines so one
// cannot overwrite the other's message.
"function sceneMsg(text,kind){"
"var el=document.getElementById('scene_msg');"
"if(!el) return;"
"el.textContent=text;"
"el.className='hint'+(kind?' '+kind:'');"
"}"

"function sceneDownload(){"
"var el=document.getElementById('buddy_scene');"
"var card={_format:'swarmclaw.scene-card',_version:SCENE_VERSION,"
"  scene:el?el.value:''};"
"var blob=new Blob([JSON.stringify(card,null,2)],{type:'application/json'});"
"var url=URL.createObjectURL(blob);"
"var a=document.createElement('a');"
"a.href=url;"
"a.download='scene.json';"
"document.body.appendChild(a);"
"a.click();"
"document.body.removeChild(a);"
"URL.revokeObjectURL(url);"
"sceneMsg('Exported.','ok');"
"}"

"function sceneUpload(ev){"
"var input=ev.target;"
"var file=input.files&&input.files[0];"
"if(!file) return;"
"var reader=new FileReader();"
"reader.onload=function(){"
"  var card;"
"  try{card=JSON.parse(reader.result)}catch(e){"
"    sceneMsg('Not valid JSON.','err');"
"    input.value='';"
"    return;"
"  }"
"  if(!card||typeof card!=='object'||Array.isArray(card)){"
"    sceneMsg('Expected a JSON object.','err');"
"    input.value='';"
"    return;"
"  }"
"  /* A scene card, or a character card: buddy_scene is what the config page "
"     calls it, scene is what the offline generator writes. */"
"  var text=card.scene!==undefined?card.scene:card.buddy_scene;"
"  if(typeof text!=='string'){"
"    sceneMsg('No scene field in this file.','err');"
"    input.value='';"
"    return;"
"  }"
"  var bytes=new TextEncoder().encode(text).length;"
"  if(bytes>SCENE_MAX){"
"    sceneMsg('Scene is '+bytes+' bytes, limit '+SCENE_MAX+'.','err');"
"    input.value='';"
"    return;"
"  }"
"  var el=document.getElementById('buddy_scene');"
"  if(el) el.value=text;"
"  sceneMsg('Loaded '+bytes+' bytes. Press Save to keep it.','ok');"
"  input.value='';"
"};"
"reader.readAsText(file);"
"}"

"function cardDownload(){"
"var card={_format:'swarmclaw.character-card',_version:CARD_VERSION};"
"CARD_KEYS.forEach(k=>{"
"  var el=document.getElementById(k);"
"  card[k]=el?el.value:'';"
"});"
"var blob=new Blob([JSON.stringify(card,null,2)],{type:'application/json'});"
"var url=URL.createObjectURL(blob);"
"var a=document.createElement('a');"
"a.href=url;"
"a.download=(card.buddy_name||'character')+'.json';"
"document.body.appendChild(a);"
"a.click();"
"document.body.removeChild(a);"
"URL.revokeObjectURL(url);"
"cardMsg('Exported.','ok');"
"}"

"function cardUpload(ev){"
"var input=ev.target;"
"var file=input.files&&input.files[0];"
"if(!file) return;"
"var reader=new FileReader();"
"reader.onload=function(){"
"  var card;"
"  try{card=JSON.parse(reader.result)}catch(e){"
"    cardMsg('Not valid JSON.','err');"
"    input.value='';"
"    return;"
"  }"
"  if(!card||typeof card!=='object'||Array.isArray(card)){"
"    cardMsg('Expected a JSON object.','err');"
"    input.value='';"
"    return;"
"  }"
"  var filled=[],problems=[];"
"  CARD_KEYS.forEach(k=>{"
"    if(card[k]===undefined||card[k]===null) return;"
"    var v=String(card[k]);"
"    /* Measure what the device stores: UTF-8 bytes, not JS characters. */"
"    var bytes=cardBytes(v);"
"    if(bytes>CARD_MAX[k]){"
"      problems.push(k.replace('buddy_','')+' is '+bytes+' bytes, limit '+CARD_MAX[k]);"
"      return;"
"    }"
"    var el=document.getElementById(k);"
"    if(el){el.value=v;filled.push(k)}"
"  });"
"  var known=CARD_KEYS.filter(k=>card[k]!==undefined&&card[k]!==null);"
"  if(!known.length){"
"    cardMsg('No character fields in this file.','err');"
"    input.value='';"
"    return;"
"  }"
"  var msg='Loaded '+filled.length+' field(s). Press Save to keep them.';"
"  if(problems.length) msg+=' Too long, skipped: '+problems.join('; ')+'.';"
"  cardMsg(msg,problems.length?'err':'ok');"
"  input.value='';"
"};"
"reader.onerror=function(){cardMsg('Could not read the file.','err');input.value=''};"
"reader.readAsText(file);"
"}"

"function save(){"
"var fields=['ssid','password','api_key','model','provider','system_prompt','tg_token',"
"'feishu_app_id','feishu_app_secret','proxy_host','proxy_port','proxy_type','search_key','tavily_key',"
"'buddy_name','buddy_bio',"
"'buddy_appearance','buddy_belongings','buddy_traits','buddy_tech_level','buddy_speech','buddy_knows',"
"'buddy_scene',"
"'buddy_cool_peer_min','buddy_cool_session_min'];"
"var boolFields=['telegram_bot','feishu_bot','buddy_privacy'];"
"var data={};"
"fields.forEach(f=>{"
"    var el=document.getElementById(f);"
"    if(el) data[f]=el.value.trim();"
"});"
"boolFields.forEach(f=>{"
"    var el=document.getElementById(f);"
"    if(el) data[f]=el.checked;"
"});"
"console.log('Saving configuration:', data);"
"document.getElementById('status').style.display='block';"
"fetch('/save',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)})"
".then(()=>{document.getElementById('status').textContent='Saved! Restarting...';})"
".catch(()=>{document.getElementById('status').textContent='Error. Please try again.';})}"
"function setFeatureAvailability(id, available){"
"var row=document.getElementById('feature_'+id);"
"var cb=document.getElementById(id);"
"if(!row || !cb){return}"
"if(available){"
"row.style.display='flex';"
"cb.disabled=false;"
"return;"
"}"
"row.style.display='none';"
"cb.checked=false;"
"cb.disabled=true;"
"}"
"function setSectionVisible(id, visible){"
"var el=document.getElementById(id);"
"if(el){"
"el.style.display = visible ? '' : 'none';"
"}"
"}"
"var featureAvailability = {};"
"function updateDependentVisibility(){"
"return;"
"}"
"function applyBuildAvailability(cfg){"
"updateDependentVisibility();"
"}"

"document.addEventListener('DOMContentLoaded', function(){"
"updateDependentVisibility();"
"});"

"loadConfig();"
"</script>"
"</body></html>";
